language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: TYPO3_VERSION=^6.2
    - php:
      env: TYPO3_VERSION=^7.6

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email:
    - breakpoint@schreibersebastian.de

before_install:
  - composer self-update
  - composer --version

before_script:
  - composer require typo3/cms=$TYPO3_VERSION
  - git checkout composer.json

script:
  - >
    echo;
    echo "Running unit tests";
    .Build/bin/phpunit --colors  -c .Build/vendor/typo3/cms/typo3/sysext/core/Build/UnitTests.xml Tests/Unit/