<?php

########################################################################
# Extension Manager/Repository config file for ext: "ssch_html5videoplayer"
#
# Auto generated by Extension Builder 2011-07-06
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
    'title' => 'HTML5Videoplayer',
    'description' => 'Create a HTML5AudioVideoplayer with Flash-Fallback.',
    'category' => 'plugin',
    'author' => 'Sebastian Schreiber',
    'author_email' => 'me@schreibersebastian.de',
    'author_company' => 'Sebastian Schreiber',
    'shy' => '',
    'dependencies' => 'cms,extbase,fluid',
    'conflicts' => '',
    'priority' => '',
    'module' => '',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'modify_tables' => '',
    'clearCacheOnLoad' => 0,
    'lockType' => '',
    'version' => '1.2.1',
    'constraints' => array(
        'depends' => array(
            'cms' => '6.2',
            'static_info_tables' => '',
        ),        
    ),
);
?>